export const SHIP_TYPE = {
  BATTLE_SHIP: 'BATTLE_SHIP',
  CRUISER: 'CRUISER',
  DESTROYER: 'DESTROYER',
  SUBMARINE: 'SUBMARINE'
}

export const SHIP_DIRECTION = {
  VERTICAL: 'VERTICAL',
  HORIZONTAL: 'HORIZONTAL'
}

export const STATE = {
  HIT: 'HIT',
  SANK: 'SANK'
}
