export const SHIP_TYPE = {
  BATTLE_SHIP: 'BATTLE_SHIP',
  CRUISER: 'CRUISER',
  DESTROYER: 'DESCTROYER',
  SUBMARINE: 'SUBMARINE'
}

export const SHIP_DIRECTION = {
  VERTICAL: 'VERTICAL',
  HORIZONTAL: 'HORIZONTAL'
}
